### PR TITLE
Use CustomEvent polyfill if necessary

### LINKED ISSUE #58: CustomEvent not support IE
when I use in IE(11 and below), it fails with:
```
location.js (7,1)  Object doesn't support this action
```

### PR DESCRIPTION
**Pull request by yuku-t**
Close #58

To support IE11

## Reference

https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill

### CODE REVIEW

**Comment by yuku-t** [comment]
Because there is `window.CustomEvent` in jest env, I cannot keep 100% coverage 😭

**Comment by jorgebucaran** [comment]
@yuku-t Why do we need to include the polyfill in the router? Surely, it must be possible to polyfill `CustomEvent` in the environment before importing @hyperapp/router.

**Comment by yuku-t** [comment]
You are right, the dependency should be noted in the README.md though

**Comment by jorgebucaran** [comment]
Yeah, that's more reasonable. I'll add it later. Thanks!

**Pull request closed without merging**
